version: '3.9'
services:
  dev-db:
    container_name: mysql
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root1234
    networks:
      - nest-test-db
networks:
  nest-test-db:
